project:
  type: website
  output-dir: docs

website:
  title: "Minnesota Land Ownership"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: county-dashboard.qmd
        text: County Dashboard
      - href: graphs.qmd
        text: Graphs
      - href: about.qmd
        text: About
    tools:
      - icon: github
        href: https://github.com/herporp88/Anders-herpor.github.io

  sidebar:
   style: docked
   search: true
   contents:
    - text: "Project Overview"
      href: index.qmd
    - text: "County Dashboard"
      href: county-dashboard.qmd
    - text: "Graphs"
      href: graphs.qmd
    - text: "About"
      href: about.qmd

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true
    toc-location: right
    page-layout: full
    smooth-scroll: true
    code-fold: false
    code-tools: false
    link-external-newwindow: false